env: dev
pid: ""
level: 4
log: /dev/stdout

http:
    main:
        addr: 127.0.0.1:8080

debug:
    addr: 127.0.0.1:12000

mysql:
    - name: main
      host: 127.0.0.1
      port: 3306
      schema: test
      user: test
      password: test
      maxidleconn: 5
      maxopenconn: 5
      maxconnttl: 50s
      interpolateparams: false
      timezone: UTC
      txisolevel: ""
      charset: utf8mb4,utf8
      timeout: 5s
      readtimeout: 5s
      writetimeout: 5s
